title: Carlo's Dev Blog
description: Un blog tecnico, senza fronzoli.
remote_theme: mmistakes/minimal-mistakes@4.20.2
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num"
author:
  name: Carlo Di Giuseppe
