title: Carlo's Dev Blog
description: Un blog tecnico, senza fronzoli.
markdown: kramdown

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
